export enum AuditEventType {
  CHECK_IN = 'CHECK_IN',
  CHECK_OUT = 'CHECK_OUT',
  OFFICE_IN = 'OFFICE_IN',
  REMOTE_IN = 'REMOTE_IN',
  GEO_REJECTION = 'GEO_REJECTION',
  MANUAL_CREATE = 'MANUAL_CREATE',
  MANUAL_UPDATE = 'MANUAL_UPDATE',
  MANUAL_DELETE = 'MANUAL_DELETE',
  STATUS_OVERRIDE = 'STATUS_OVERRIDE',
  REMOTE_APPROVE = 'REMOTE_APPROVE',
  REMOTE_REJECT = 'REMOTE_REJECT',
}
