export enum AuditEventType {
  CHECK_IN = 'CHECK_IN',
  CHECK_OUT = 'CHECK_OUT',
  OFFICE_IN = 'OFFICE_IN',
  REMOTE_IN = 'REMOTE_IN',
  GEO_REJECTION = 'GEO_REJECTION',
  MANUAL_CREATE = 'MANUAL_CREATE',
  MANUAL_UPDATE = 'MANUAL_UPDATE',
  MANUAL_DELETE = 'MANUAL_DELETE',
  STATUS_OVERRIDE = 'STATUS_OVERRIDE',
  REMOTE_APPROVE = 'REMOTE_APPROVE',
  REMOTE_REJECT = 'REMOTE_REJECT',

  // Auto-checkout engine (auto-checkout.md)
  AUTO_CHECKOUT = 'AUTO_CHECKOUT',
  CORRECTION_SUBMITTED = 'CORRECTION_SUBMITTED',
  CORRECTION_APPROVED = 'CORRECTION_APPROVED',
  CORRECTION_REJECTED = 'CORRECTION_REJECTED',
  CORRECTION_CLOSED = 'CORRECTION_CLOSED',

  // Daily materialization engine (attendance-daily-cron.md)
  AUTO_ABSENT_MARK = 'AUTO_ABSENT_MARK',
  AUTO_LEAVE_SYNC = 'AUTO_LEAVE_SYNC',
  AUTO_HOLIDAY_SYNC = 'AUTO_HOLIDAY_SYNC',
  AUTO_WEEKLY_OFF_MARK = 'AUTO_WEEKLY_OFF_MARK',
}
