export enum GeoStatus {
  VALID = 'VALID',
  OUTSIDE_RADIUS = 'OUTSIDE_RADIUS',
  GPS_DISABLED = 'GPS_DISABLED',
  MOCK_LOCATION = 'MOCK_LOCATION',
  REJECTED = 'REJECTED',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
}
