export enum LeadStatus {
  NEW = 'NEW',
  CONTACTED = 'CONTACTED',
  DEMO_SCHEDULED = 'DEMO_SCHEDULED',
  DEMO_COMPLETED = 'DEMO_COMPLETED',
  PROPOSAL_SENT = 'PROPOSAL_SENT',
  NEGOTIATION = 'NEGOTIATION',
  CONTRACT_SENT = 'CONTRACT_SENT',
  WON = 'WON',
  LOST = 'LOST',
  ON_HOLD = 'ON_HOLD',
}
