export enum LedgerEntryType {
  INITIAL_GRANT = 'INITIAL_GRANT',
  CARRY_FORWARD = 'CARRY_FORWARD',
  MONTHLY_ACCRUAL = 'MONTHLY_ACCRUAL',
  MANUAL_ADJUSTMENT = 'MANUAL_ADJUSTMENT',
  REQUEST_HOLD = 'REQUEST_HOLD',
  REQUEST_RELEASE = 'REQUEST_RELEASE',
  REQUEST_CONSUME = 'REQUEST_CONSUME',
  LAPSE = 'LAPSE',
}

export enum LedgerDirection {
  CREDIT = 'CREDIT',
  DEBIT = 'DEBIT',
}
