export enum StorageProvider {
  S3 = 'S3',
  LOCAL = 'LOCAL',
  GCS = 'GCS',
  DATABASE = 'DATABASE',
}

export enum FolderType {
  ENTERPRISE_LOGO = 'ENTERPRISE_LOGO',
  ORGANIZATION_LOGO = 'ORGANIZATION_LOGO',
  EMPLOYEE_IMAGE = 'EMPLOYEE_IMAGE',
  EMPLOYEE_DOCUMENT = 'EMPLOYEE_DOCUMENT',
  ORGANIZATION_DOCUMENT = 'ORGANIZATION_DOCUMENT',
  REIMBURSEMENT_DOCUMENT = 'REIMBURSEMENT_DOCUMENT',
  FEEDBACK_ATTACHMENT = 'FEEDBACK_ATTACHMENT',
  LETTER_SIGNATURE = 'LETTER_SIGNATURE',
  LETTER_DOCUMENT = 'LETTER_DOCUMENT',
  OFFER_DOCUMENT = 'OFFER_DOCUMENT',
}

const IMAGE_FOLDER_TYPES: ReadonlySet<FolderType> = new Set([
  FolderType.ENTERPRISE_LOGO,
  FolderType.ORGANIZATION_LOGO,
  FolderType.EMPLOYEE_IMAGE,
  FolderType.LETTER_SIGNATURE,
]);

export function isImageFolderType(folderType: FolderType): boolean {
  return IMAGE_FOLDER_TYPES.has(folderType);
}
