export enum StorageProvider {
  S3 = 'S3',
  LOCAL = 'LOCAL',
  GCS = 'GCS',
}

export enum FolderType {
  ENTERPRISE_LOGO = 'ENTERPRISE_LOGO',
  ORGANIZATION_LOGO = 'ORGANIZATION_LOGO',
  EMPLOYEE_IMAGE = 'EMPLOYEE_IMAGE',
  EMPLOYEE_DOCUMENT = 'EMPLOYEE_DOCUMENT',
  ORGANIZATION_DOCUMENT = 'ORGANIZATION_DOCUMENT',
}
