export enum AuditLogModule {
  // Security
  AUTH = 'AUTH',
  SESSION = 'SESSION',

  // People
  EMPLOYEE = 'EMPLOYEE',
  ORGANIZATION = 'ORGANIZATION',
  DEPARTMENT = 'DEPARTMENT',
  DESIGNATION = 'DESIGNATION',

  // Access Control
  ROLE = 'ROLE',
  PERMISSION = 'PERMISSION',
  USER_ROLE = 'USER_ROLE',

  // Leave
  LEAVE_CONFIG = 'LEAVE_CONFIG',
  LEAVE_REQUEST = 'LEAVE_REQUEST',
  LEAVE_BALANCE = 'LEAVE_BALANCE',

  // Attendance
  ATTENDANCE = 'ATTENDANCE',
  SHIFT = 'SHIFT',

  // Payroll
  PAYROLL = 'PAYROLL',
  SALARY = 'SALARY',

  // Reimbursement
  REIMBURSEMENT = 'REIMBURSEMENT',

  // HR
  ANNOUNCEMENT = 'ANNOUNCEMENT',
  COMPANY_POLICY = 'COMPANY_POLICY',
  HOLIDAY = 'HOLIDAY',
  HR_TEMPLATE = 'HR_TEMPLATE',
  DOCUMENT = 'DOCUMENT',

  // Project
  PROJECT = 'PROJECT',
  CLIENT = 'CLIENT',

  // Billing
  BILLING = 'BILLING',
  SUBSCRIPTION = 'SUBSCRIPTION',

  // Platform
  PLATFORM_ENTERPRISE = 'PLATFORM_ENTERPRISE',
  PLATFORM_PLAN = 'PLATFORM_PLAN',
  PLATFORM_SETUP = 'PLATFORM_SETUP',

  // Letter Management
  LETTER_MANAGEMENT = 'LETTER_MANAGEMENT',
  OFFER_LETTER = 'OFFER_LETTER',
  LETTER_SIGNATORY = 'LETTER_SIGNATORY',

  // Offer Management
  OFFER_MANAGEMENT = 'OFFER_MANAGEMENT',
}
