import {
    Entity,
    Column,
    ManyToOne,
    JoinColumn,
    Index,
} from 'typeorm';
import { Status } from '../../../common/enums/status.enum';
import { Organization } from '../../organization/entities/organization.entity';

/**
 * Designation Entity
 *
 * Represents a job title / designation within an organization.
 *
 * Design decisions:
 * - Soft delete: status is set to INACTIVE instead of physical deletion.
 * - org_id + code unique index: enforces no duplicate codes within the same org at DB level.
 * - department_id is nullable: department linkage is optional in Phase 1.
 */
@Entity('designations')
@Index('IDX_DESIGNATION_ORG_CODE', ['org_id', 'code'], { unique: true })
export class Designation {
    // Primary key — UUID auto-generated by the database
    @Column({ primary: true, type: 'uuid', generated: 'uuid' })
    id: string;

    // Reference to the owning organization (required)
    @Column({ type: 'uuid' })
    org_id: string;

    // Many-to-One: each designation belongs to one organization
    @ManyToOne(() => Organization, { eager: false })
    @JoinColumn({ name: 'org_id' })
    organization: Organization;

    // Linked department — optional in Phase 1, must belong to the same org
    @Column({ type: 'uuid', nullable: true })
    department_id: string | null;

    /**
     * Short code for the designation, unique within an organization.
     * Immutable once created (enforced at the service layer).
     * Examples: "SWE", "PM", "HR-01"
     */
    @Column({ type: 'varchar', length: 50 })
    code: string;

    // Full designation title — e.g. "Software Engineer", "Product Manager"
    @Column({ type: 'varchar', length: 255 })
    title: string;

    // Optional seniority / band level — e.g. "L1", "L2", "Senior"
    @Column({ type: 'varchar', length: 50, nullable: true })
    level: string | null;

    /**
     * Lifecycle status of the designation.
     * ACTIVE  — can be assigned to employees.
     * INACTIVE — soft-deleted; cannot be assigned to new employees.
     */
    @Column({
        type: 'enum',
        enum: Status,
        default: Status.ACTIVE,
    })
    status: Status;

    // Optional free-text description of the designation's responsibilities
    @Column({ type: 'text', nullable: true })
    description: string | null;

    // Timestamp of record creation
    @Column({ type: 'timestamp', default: () => 'CURRENT_TIMESTAMP' })
    created_at: Date;

    // Timestamp of the last update
    @Column({
        type: 'timestamp',
        default: () => 'CURRENT_TIMESTAMP',
        onUpdate: 'CURRENT_TIMESTAMP',
    })
    updated_at: Date;
}
