import {
    Entity,
    Column,
    ManyToOne,
    JoinColumn,
    Index,
} from 'typeorm';
import { Status } from '../../../common/enums/status.enum';
import { Organization } from '../../organization/entities/organization.entity';
import { BaseEntity } from 'src/common/entities/base.entity';

/**
 * Designation Entity
 *
 * Represents a job title / designation within an organization.
 *
 * Design decisions:
 * - Soft delete: status is set to INACTIVE instead of physical deletion.
 * - org_id + code unique index: enforces no duplicate codes within the same org at DB level.
 * - department_id is nullable: department linkage is optional in Phase 1.
 */
@Entity('designations')
@Index('IDX_DESIGNATION_ORG_CODE', ['org_id', 'code'], { unique: true })
export class Designation extends BaseEntity {
    // Primary key — UUID auto-generated by the database


    // Reference to the owning organization (required)
    @Column({ type: 'uuid' })
    org_id: string;

    // Many-to-One: each designation belongs to one organization
    @ManyToOne(() => Organization, { eager: false })
    @JoinColumn({ name: 'org_id' })
    organization: Organization;

    // Linked department — optional in Phase 1, must belong to the same org
    @Column({ type: 'uuid', nullable: true })
    department_id: string | null;

    /**
     * Short code for the designation, unique within an organization.
     * Immutable once created (enforced at the service layer).
     * Examples: "SWE", "PM", "HR-01"
     */

    // Full designation title — e.g. "Software Engineer", "Product Manager"
    @Column({ type: 'varchar', length: 255 })
    title: string;

    @Column({ type: 'boolean', default: false })
    is_deleted: boolean;

}
